import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Table from "../src/components/Table";
import { useGetAllDataQuery, GetAllDataQuery } from "../src/generated/graphql";
import { graphqlRequestClient } from "../src/lib/clients/graphqlRequestClient";

const Home: NextPage = () => {
  const { data } = useGetAllDataQuery<GetAllDataQuery, Error>(
    graphqlRequestClient,
    {}
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>RaraLabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table data={data} />
    </div>
  );
};

export default Home;
